services:
  web1:
    restart: on-failure
    build: ../02-chat-app
    hostname: web1
    ports:
      - "8081:3000"
  web2:
    restart: on-failure
    build: ../02-chat-app
    hostname: web2
    ports:
      - "8082:3000"
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - web1
      - web2
